borrowingWebsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('shop.urls')),
    url(r'^account/', include('account.urls')),
    # Social authentication
    url(r'^auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'shop'

urlpatterns = [
    url(r'^create/$', views.product_create, name='product_create'),
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^categories/(?P<location_slug>[-\w]+)/$', views.product_list, name='product_list_by_location'),
    url(r'^(?P<uuid>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import RegexValidator
from django.core.validators import MinValueValidator
from django.core.validators import MaxValueValidator
from shop.choices import STATUS_CHOICES
from django.conf import settings
from django.utils.text import slugify
import uuid

# Create your models here.


class Location(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'location'
        verbose_name_plural = 'locations'

    def get_absolute_url(self):
        return reverse('shop:product_list_by_location', args=[self.slug])

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    uuid = models.CharField(max_length=200,
                            default=int(uuid.uuid4().time_low),
                            editable=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             default=1,
                             on_delete=models.CASCADE)
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    # image = models.FileField(upload_to='products/%Y/%m/%d/%f', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,
                                decimal_places=0,
                                null=True,
                                blank=True)
    price_per_day = models.DecimalField(max_digits=10,
                                        decimal_places=0,
                                        null=True,
                                        blank=True)
    price_per_week = models.DecimalField(max_digits=10,
                                         decimal_places=0,
                                         null=True,
                                         blank=True)
    price_per_month = models.DecimalField(max_digits=10,
                                          decimal_places=0,
                                          null=True,
                                          blank=True)
    price_per_year = models.DecimalField(max_digits=10,
                                         decimal_places=0,
                                         null=True,
                                         blank=True)
    stock = models.PositiveIntegerField(default=1)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    location = models.ForeignKey(Location,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    phone_regex = RegexValidator(regex=r'^\+?09?\d{9,15}$',
                                 message="Phone number must be entered in \
                                 the format: '09123456789'. Up to 11 \
                                 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex],
                                    max_length=11, help_text="Enter your \
                                    number formatted like: 09123456789")
    status = models.IntegerField(choices=STATUS_CHOICES,
                                 default='1')
    health = models.PositiveIntegerField(default=50,
                                         validators=[MinValueValidator(0),
                                                     MaxValueValidator(100),
                                                     ],
                                         help_text="How healthy \
                                         is your thing out of 100?",
                                         blank=False)
    condition = models.TextField(blank=True)

    class Meta:
        ordering = ('-created',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.uuid, self.slug])

    def promoted(self):
        if self.status == 2:
            return True
        else:
            return False

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class Gallery(models.Model):
    product = models.ForeignKey(Product,
                                default=None,
                                on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/%Y/%m/%d/%f',
                              verbose_name='Image',
                              blank=True,
                              null=True)

shop/forms.py
from django import forms
from .models import Product, Gallery


class AddProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            "name",
            "category",
            "price_per_day",
            "price_per_week",
            "price_per_month",
            "price_per_year",
            "location",
            "phone_number",
            "health",
        ]


class GalleryForm(forms.ModelForm):
    image = forms.ImageField(label='Image', widget=forms.ClearableFileInput(
        attrs={
            'blank': 'True',
            'null': 'True',
        }
    ))

    class Meta:
        model = Gallery
        fields = ['image', ]

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product, Location, Gallery
from django.contrib import messages
from django.http import HttpResponseRedirect
from .forms import AddProductForm, GalleryForm
from django.contrib.auth.decorators import login_required
# from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.forms import modelformset_factory

# Create your views here.


def product_list(request, category_slug=None, location_slug=None):
    category = None
    categories = Category.objects.all()
    location = None
    locations = Location.objects.all()
    products = Product.objects.filter(available=True)
    # paginator = Paginator(products, 4) # Number of objects on a page
    page = request.GET.get('page', 1)
    query = request.GET.get("q")
    if query:
        products = products.filter(
              Q(name__contains=query)
            | Q(description__contains=query)
            | Q(category__name__contains=query)
            ).distinct()
    # try:
    #     products = paginator.page(page)
    # except PageNotAnInteger:
    #     # If page is not an integer deliver the first page
    #     products = paginator.page(1)
    # except EmptyPage:
    #     # If page is out of range deliver last page of results
    #     products = paginator.page(paginator.num_pages)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    elif location_slug:
        location = get_object_or_404(Location, slug=location_slug)
        products = products.filter(location=location)
    context = {'category': category,
               'categories': categories,
               'location': location,
               'locations': locations,
               'products': products,
               'page': page,
               }
    return render(request, 'shop/product/list.html', context)


def product_detail(request, uuid, slug):
    product = get_object_or_404(Product, uuid=uuid, slug=slug, available=True)
    return render(request, 'shop/product/detail.html', {'product': product})


@login_required
def product_create(request):

    ImageFormSet = modelformset_factory(Gallery, form=GalleryForm, extra=3)
    if request.method == 'POST':

        addProductForm = AddProductForm(request.POST)
        formset = ImageFormSet(request.POST, request.FILES,
                               queryset=Gallery.objects.none())

        if addProductForm.is_valid() and formset.is_valid():
            add_product_form = addProductForm.save(commit=False)
            add_product_form.user = request.user
            add_product_form.save()

            for form in formset.cleaned_data:
                try:
                    image = form['image']
                except KeyError:
                    break
                photo = Gallery(product=add_product_form, image=image)
                photo.save()
            messages.success(request,
                             "Your thing was successfuly uploaded!")
            return HttpResponseRedirect("/")
        else:
            print (addProductForm.errors, formset.errors)
    else:
        addProductForm = AddProductForm()
        formset = ImageFormSet(queryset=Gallery.objects.none())
    return render(request, 'shop/product/create.html',
                  {'addProductForm': addProductForm, 'formset': formset})

shop/templates/shop/product/create.html
{% extends "shop/base.html" %}

{% block title %}Log-in | Borrow{% endblock %}

{% block content %}
<div class="col-lg-12">
  <form action="." method="post" enctype="multipart/form-data">
    <h1>Add thing</h1>
    <hr>
    {% csrf_token %}
    {% for hidden in addProductForm.hidden_fields %}
        {{ hidden }}
    {% endfor %}

    {% for field in addProductForm %}
        {{ field }} <br />
    {% endfor %}

    {{ formset.management_form }}
    {% for form in formset %}
        {{ form }}
    {% endfor %}
    <button class="btn btn-primary " type="submit">Add</button>
  </form>
</div>
{% endblock %}

shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block content %}
<div class="container mt-5">
  <div id="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url "shop:product_list" %}">Home</a></li>
      <li class="breadcrumb-item"><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></li>
      <li class="breadcrumb-item active">{{ product.name }}</li>
    </ol>
  </div>
  <div class="row">


    <div class="col-lg-5 col-md-4 col-sm-6 col-xs-12">
      {% if product.gallery_set.all %}
        {% for p in product.gallery_set.all %}
          <div class="">
            <a href="{{ p.image.url }}">
              <img class="card-img-top" src="
                {{ p.image.url }}
              ">
            </a>
          </div>
        {% endfor %}
      {% else %}
        <div class="">
          <img class="card-img-top" src="
            {% static "css/img/no_image.jpg" %}
          ">
        </div>
      {% endif %}
    </div>

    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
      <h2>{{ product.name }}</h2>
      <h5>
        <a class="badge badge-primary" href="{{ product.category.get_absolute_url }}">{{ product.category }}</a>
        {% if product.location %}
          <small>for rent in</small>
          <a class="badge badge-primary" href="{{ product.location.get_absolute_url }}">{{ product.location }}</a>
        {% else %}
          <a class="badge badge-primary" href="#">Iran</a>
        {% endif %}
      </h5>
      <p>
        <h5>
          <!-- <strike class="text-danger price">${{ product.price }}</strike>
          &nbsp;
          &nbsp; -->
          <!-- <span class="text-success price">${{ product.price }}</span> -->
        </h5>
      </p>
      <div class="health col-lg-12 col-md-4 col-sm-6 col-xs-6">
        <h6>Health</h6>
        <div class="progress">
          <div class="progress-bar" role="progressbar" style="width: {{ product.health }}%"  aria-valuemin="0" aria-valuemax="10">{{ product.health }}%</div>
        </div>
      </div>
      </br>
      {{ product.description|linebreaks }}
      {% if product.condition %}
        <div id=condition class="card border-danger text-muted text-center">
          <h6 class="card-header">Conditions</h6>
          <div class="card-body">
            <p class="card-text">{{ product.condition }}</p>
          </div>
        </div>
      {% endif %}
      </br>
      <ul class="list-group">
        {% if product.price_per_day %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <p>Price per <strong>day</strong></p>
          <span class="badge badge-primary badge-pill">${{ product.price_per_day }}</span>
        </li>
        {% endif %}
        {% if product.price_per_week %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <p>Price per <strong>week</strong></p>
          <span class="badge badge-primary badge-pill">${{ product.price_per_week }}</span>
        </li>
        {% endif %}
        {% if product.price_per_month %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <p>Price per <strong>month</strong></p>
          <span class="badge badge-primary badge-pill">${{ product.price_per_month }}</span>
        </li>
        {% endif %}
        {% if product.price_per_year %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <p>Price per <strong>year</strong></p>
          <span class="badge badge-primary badge-pill">${{ product.price_per_year }}</span>
        </li>
        {% endif %}
      </ul>
      </br>
      <button class="btn btn-primary btn-block" type="button" data-toggle="collapse" data-target="#collapseButton" aria-expanded="false" aria-controls="collapseButton">
        Show owner's phone number
      </button>
      <div class="collapse" id="collapseButton">
        <div class="card card-body">
          {{ product.phone_number }}
        </div>
      </div>
    </div>

  </div>
</div>
{% endblock %}

shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{% if category %}
  {{ category.name }} | Borrow
{% elif location %}
  {{ location.name }} | Borrow
{% else %}
  All | Borrow
{% endif %}
{% endblock %}

{% block jombotron %}
  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Album example</h1>
      <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
      <p>
        <a href="#" class="btn btn-primary my-2">Main call to action</a>
        <a href="#" class="btn btn-secondary my-2">Secondary action</a>
      </p>
    </div>
  </section>
{% endblock %}

{% block map %}
      <div class="container">
        <div class="row">
          <div id="mapdiv" class="map_div col-lg-12 col-md-12 col-sm-12 col-xs-12 my-3"></div>
      </div>
    </div>
{% endblock %}

{% block content %}
  <div id="sidebar" class="col-lg-12 btn-group m-3 p-1 border border-secondary rounded d-flex">
    <div class="dropdown show">
      <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Categories
      </a>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
        <a class="dropdown-item" href="{% url "shop:product_list" %}">All</a>
        {% for c in categories %}
          <a href="{{ c.get_absolute_url }}" class="dropdown-item">{{ c.name }}</a>
        {% endfor %}
      </div>
    </div>
    &nbsp;
    <div class="dropdown show">
      <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Locations
      </a>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
        <a class="dropdown-item" href="{% url "shop:product_list" %}">Iran</a>
        {% for l in locations %}
          <a href="{{ l.get_absolute_url }}" class="dropdown-item">{{ l.name }}</a>
        {% endfor %}
      </div>
    </div>
    &nbsp;
    <form class="ml-auto" action="" method="GET">
      <div class="input-group ml-auto">
        <input class="form-control" type="text" name="q" placeholder="Search" aria-describedby="basic-addon1" value="{{ request.GET.q }}">
        <div class="input-group-prepend">
          <button class="btn btn-outline-secondary" type="submit" aria-describedby="basic-addon2">Search</button>
        </div>
      </div>
    </form>
  </div>

  <div class="container-fluid">
    <h2>
      {% if category %}
        {{ category.name }}
      {% elif location %}
        {{ location.name }}
      {% else %}
        All
      {% endif %}
    </h2>
    <hr noshade>

	<main class="cd-main-content">
    <div class="cd-tab-filter-wrapper">
      <div class="cd-tab-filter">
        <ul class="cd-filters">

          <li class="filter"><a class="selected" href="#0" data-type="all">All</a></li>
          {% for category in categories %}
            <li class="filter" data-filter=".{{ category.name }}"><a href="#0" data-type="color-1">{{ category.name }}</a></li>
          {% endfor %}
        </ul> <!-- cd-filters -->
      </div> <!-- cd-tab-filter -->
    </div> <!-- cd-tab-filter-wrapper -->

  		<section class="cd-gallery grid">
        <ul>

      {% for product in products %}
      <div class="grid-item col-lg-3 col-md-4 col-sm-6 col-xs-12">
      <li class=" mix {{ product.category }}">

        {% if product.promoted %}
        <div class="card bg-primary mb-4 shadow-lg">
        {% else %}
        <div class="card mb-4 shadow-sm">
        {% endif %}
          <a href="{{ product.get_absolute_url }}">
            {% if product.gallery_set.all %}
                <div class="">
                  <img class="card-img-top" src="
                  {% for p in product.gallery_set.all %}
                    {{ p.image.url }}"
                  {% endfor %}>
                </div>
            {% else %}
              <div class="">
                <img class="card-img-top" src="
                  {% static "css/img/no_image.jpg" %}
                ">
              </div>
            {% endif %}
          </a>
          <div class="card-body">
            {% if product.promoted %}
            <a class="text-white card-link" href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
            {% else %}
             <a class="card-link" href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
            {% endif %}

           <div class="d-flex justify-content-between align-items-center pt-3">
             <div class="btn-group">
               <!-- <button type="button" class="btn btn-sm btn-danger">{{ product.urgent_situation }}</button> -->
               <!-- {% if product.promoted %}
                 <small class="badge badge-danger">Promoted</small>
               {% endif %} -->
               {{ product.category }}
             </div>
             {% if product.price_per_day %}
               <small class="text-muted">From ${{ product.price_per_day }}</small>
             {% elif product.price %}
               <small class="text-muted">${{ product.price }}</small>
             {% endif %}
           </div>
          </div>
        </div>
      </li>
      </div>
      {% endfor %}
    </ul>
    <div class="cd-fail-message">No results found</div>
    </section>

    </main>
  </div>
  <!-- <div class="col-lg-4 pagination">
    <span class="step-links">
      {% if products.has_previous %}
        <a class="btn btn-outline-primary" href="?page={{ products.previous_page_number }}&q={{ request.GET.q }}">Previous</a>
      {% else %}
        <a class="btn btn-outline-secondary disabled">Previous</a>
      {% endif %}
      <span class="current">
        Page {{ products.number }} of {{ products.paginator.num_pages }}.
      </span>
      {% if products.has_next %}
        <a class="btn btn-outline-primary" href="?page={{ products.next_page_number }}&q={{ request.GET.q }}">Next</a>
      {% else %}
        <a class="btn btn-outline-secondary disabled">Next</a>
      {% endif %}
    </span>
  </div> -->
{% endblock %}