borrowingWebsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('shop.urls')),
    url(r'^account/', include('account.urls')),
    # Social authentication
    url(r'^auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'shop'

urlpatterns = [
    url(r'^create/$', views.product_create, name='product_create'),
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^categories/(?P<location_slug>[-\w]+)/$', views.product_list, name='product_list_by_location'),
    url(r'^(?P<uuid>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import RegexValidator
from django.core.validators import MinValueValidator
from django.core.validators import MaxValueValidator
from shop.choices import STATUS_CHOICES
from django.conf import settings
from django.utils.text import slugify
import uuid

# Create your models here.


class Location(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'location'
        verbose_name_plural = 'locations'

    def get_absolute_url(self):
        return reverse('shop:product_list_by_location', args=[self.slug])

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    uuid = models.CharField(max_length=200,
                            default=int(uuid.uuid4().time_low),
                            editable=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             default=1,
                             on_delete=models.CASCADE)
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    # image = models.FileField(upload_to='products/%Y/%m/%d/%f', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,
                                decimal_places=0,
                                null=True,
                                blank=True)
    price_per_day = models.DecimalField(max_digits=10,
                                        decimal_places=0,
                                        null=True,
                                        blank=True)
    price_per_week = models.DecimalField(max_digits=10,
                                         decimal_places=0,
                                         null=True,
                                         blank=True)
    price_per_month = models.DecimalField(max_digits=10,
                                          decimal_places=0,
                                          null=True,
                                          blank=True)
    price_per_year = models.DecimalField(max_digits=10,
                                         decimal_places=0,
                                         null=True,
                                         blank=True)
    stock = models.PositiveIntegerField(default=1)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    location = models.ForeignKey(Location,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    phone_regex = RegexValidator(regex=r'^\+?09?\d{9,15}$',
                                 message="Phone number must be entered in \
                                 the format: '09123456789'. Up to 11 \
                                 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex],
                                    max_length=11, help_text="Enter your \
                                    number formatted like: 09123456789")
    status = models.IntegerField(choices=STATUS_CHOICES,
                                 default='1')
    health = models.PositiveIntegerField(default=50,
                                         validators=[MinValueValidator(0),
                                                     MaxValueValidator(100),
                                                     ],
                                         help_text="How healthy \
                                         is your thing out of 100?",
                                         blank=False)
    condition = models.TextField(blank=True)

    class Meta:
        ordering = ('-created',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.uuid, self.slug])

    def promoted(self):
        if self.status == 2:
            return True
        else:
            return False

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class Gallery(models.Model):
    product = models.ForeignKey(Product,
                                default=None,
                                on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/%Y/%m/%d/%f',
                              verbose_name='Image',
                              blank=True,
                              null=True)

shop/forms.py
from django import forms
from .models import Product, Gallery


class AddProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            "name",
            "category",
            "price_per_day",
            "price_per_week",
            "price_per_month",
            "price_per_year",
            "location",
            "phone_number",
            "health",
        ]


class GalleryForm(forms.ModelForm):
    image = forms.ImageField(label='Image', widget=forms.ClearableFileInput(
        attrs={
            'blank': 'True',
            'null': 'True',
        }
    ))

    class Meta:
        model = Gallery
        fields = ['image', ]

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product, Location, Gallery
from django.contrib import messages
from django.http import HttpResponseRedirect
from .forms import AddProductForm, GalleryForm
from django.contrib.auth.decorators import login_required
# from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.forms import modelformset_factory

# Create your views here.


def product_list(request, category_slug=None, location_slug=None):
    category = None
    categories = Category.objects.all()
    location = None
    locations = Location.objects.all()
    products = Product.objects.filter(available=True)
    # paginator = Paginator(products, 4) # Number of objects on a page
    page = request.GET.get('page', 1)
    query = request.GET.get("q")
    if query:
        products = products.filter(
              Q(name__contains=query)
            | Q(description__contains=query)
            | Q(category__name__contains=query)
            ).distinct()
    # try:
    #     products = paginator.page(page)
    # except PageNotAnInteger:
    #     # If page is not an integer deliver the first page
    #     products = paginator.page(1)
    # except EmptyPage:
    #     # If page is out of range deliver last page of results
    #     products = paginator.page(paginator.num_pages)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    elif location_slug:
        location = get_object_or_404(Location, slug=location_slug)
        products = products.filter(location=location)
    context = {'category': category,
               'categories': categories,
               'location': location,
               'locations': locations,
               'products': products,
               'page': page,
               }
    return render(request, 'shop/product/list.html', context)


def product_detail(request, uuid, slug):
    product = get_object_or_404(Product, uuid=uuid, slug=slug, available=True)
    return render(request, 'shop/product/detail.html', {'product': product})


@login_required
def product_create(request):

    ImageFormSet = modelformset_factory(Gallery, form=GalleryForm, extra=3)
    if request.method == 'POST':

        addProductForm = AddProductForm(request.POST)
        formset = ImageFormSet(request.POST, request.FILES,
                               queryset=Gallery.objects.none())

        if addProductForm.is_valid() and formset.is_valid():
            add_product_form = addProductForm.save(commit=False)
            add_product_form.user = request.user
            add_product_form.save()

            for form in formset.cleaned_data:
                try:
                    image = form['image']
                except KeyError:
                    break
                photo = Gallery(product=add_product_form, image=image)
                photo.save()
            messages.success(request,
                             "Your thing was successfuly uploaded!")
            return HttpResponseRedirect("/")
        else:
            print (addProductForm.errors, formset.errors)
    else:
        addProductForm = AddProductForm()
        formset = ImageFormSet(queryset=Gallery.objects.none())
    return render(request, 'shop/product/create.html',
                  {'addProductForm': addProductForm, 'formset': formset})

shop/templates/shop/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>
      {% block title %}
        {% if product.name %}{{ product.name }} | Borrow{% else %}Borrow{% endif %}
      {% endblock %}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "css/blog.css" %}" rel="stylesheet">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300' rel='stylesheet' type='text/css' />

    <!-- Filtering resource style -->
    <link rel="stylesheet" href="{% static "css/style.css" %}">

    <!-- Modernizr -->
    <!-- <script src="{% static "js/modernizr.js" %}"></script> -->
    <!-- ammap js directory -->
    <script src="{% static "ammap/ammap.js" %}" type="text/javascript"></script>

    <!--ammap map directory -->
    <script src="{% static "ammap/maps/js/iranHigh.js" %}" type="text/javascript"></script>

    <!--ammap css directory -->
    <link rel="stylesheet" href="{% static "ammap/ammap.css" %}" type="text/css" media="all" />
  </head>

  <body>

    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">About</h4>
              <p class="text-muted">Why buy it? when you can borrow it.</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Contact</h4>
              <ul class="list-unstyled">
                <li><a href="#" class="text-white">Follow on Twitter</a></li>
                <li><a href="#" class="text-white">Like on Facebook</a></li>
                <li><a href="#" class="text-white">Email</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
          <a class="btn btn-primary btn-sm" href="{% url "shop:product_create" %}">Add things</a>
          <a href="{% url "shop:product_list" %}" class="navbar-brand d-flex align-items-center">
            <strong>Borrow</strong>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

    <div id="login_part">
      {% if request.user.is_authenticated %}
        <a href="{% url "dashboard" %}">My dashboard</a>
      {% endif %}
      <span class="user">
        {% if request.user.is_authenticated %}
          Hello
          {% if request.user.first_name %}
            {{ request.user.first_name }},
          {% else %}
            {{ request.user.username }},
          {% endif %}
          <a href="{% url "logout" %}">Logout</a>
        {% else %}
          <a href="{% url "login" %}">Log-in</a>
        {% endif %}
      </span>
    </div>

    {% if messages %}
      <div class="alert alert-secondary mx-4">
        {% for message in messages %}
          <span class="{{ message.tags }}">
            {{ message|safe }}
          </span>
        {% endfor %}
      </div>
    {% endif %}

    <main role="main">

      {% block map %}
      {% endblock %}

      <div class="album py-5 bg-light">
        <div class="container">
          <div class="row">
            {% block content %}
            {% endblock %}
          </div>
        </div>
      </div>

    </main>

    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
        <p>&copy; by <strong>Borrow</strong>, All rights reseved.</p>
        <!-- <p>New to Bootstrap? <a href="../../">Visit the homepage</a> or read our <a href="../../getting-started/">getting started guide</a>.</p> -->
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src={% static "js/jquery-slim.min.js" %}><\/script>')</script>
    <script src="{% static "js/popper.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="{% static "js/holder.min.js" %}"></script>

    <script src="{% static "js/main.js" %}"></script>

    <!-- Jquery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- Masonry -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/masonry/4.2.2/masonry.pkgd.min.js"></script>

    <!-- Filtering resource jQuery -->
    <script src="{% static "js/jquery.mixitup.min.js" %}"></script>
    <script src="{% static "js/cd_main.js" %}"></script>

  </body>
</html>